version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: tmtmt/rust-wasm-bindgen:0.2.28

jobs:
  build-and-test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm run test
      - persist_to_workspace:
          root: ~/repo
          paths:
            - package.json
            - README.md
            - lib

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  workflow:
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /^v.*/

      - deploy:
          requires:
            - build-and-test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
