version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: jibbow/rust-wasm32-unknown-unknown

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Headless Chrome
          command: |
            sudo apt install libappindicator3-1
	          curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
	          sudo dpkg -i google-chrome.deb
	          sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
	          rm google-chrome.deb
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm run test
