version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: jibbow/rust-wasm32-unknown-unknown

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm run test
